name: commit

# on: [push]
on:
  push:
    branches-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create file
      run: |
        mkdir -p date
        date > date/date.txt
    - name: Commit files
      run: |
        git config --local user.email "suzucan2020@users.noreply.github.com"
        git config --local user.name "suzucan2020"
        git add .
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
