name: screenshot-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot.png
    - name: ls
      run: ls -al
