name: screenshot-ci

on: [push]

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest]
        coinname: [a,b,c,d]
        width: [1200]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot-${{ matrix.os }}-${{ matrix.width }}-${{matrix.coinname}}.png
        width: ${{ matrix.width }}
