name: screenshot-ci

on: [push]

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest]
        coinname: [btc,xrp,eth,xem]
        width: [1200]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://bitflyer.com/ja-jp/ex/buysell/${{matrix.coinname}}
        destination: screenshot-${{ matrix.os }}-${{ matrix.width }}-${{matrix.coinname}}.png
        width: ${{ matrix.width }}
        
    - name: download
      uses: actions/download-artifact@v2
      with:
        name: screenshot-${{ matrix.os }}-${{ matrix.width }}-${{matrix.coinname}}
        
    - name: ls
      run: ls -al
      
  job2:
    name: job2
    needs:
      -  screenshot
    runs-on: ubuntu-latest
    steps:
    - name: ls
      run: ls -al
